FROM node:22-bookworm-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm config set registry https://registry.npmmirror.com
RUN npm ci --omit=dev
RUN npm install -g pm2

COPY . .

RUN chown -R node:node /usr/src/app
USER node

EXPOSE 3050 3051

CMD ["pm2-runtime", "start", "ecosystem.config.cjs"]
